### ISSUE TITLE
Add 'View on Etherscan/Blockscount' to external links

### ISSUE THREAD

**Issue by elena-zh** [gnosis/gp-ui#1021]
Discussed in https://github.com/gnosis/gp-ui/pull/1011#issuecomment-1026766049

Add 'View on Etherscan/Blockscount' to external links. Apply changes to 
 - Address top link in User details page 
 - Tx  top link in Transaction detail page. 
 - Contract link in the app footer
![image](https://user-images.githubusercontent.com/70885163/153012908-ba8964c5-bebc-4179-879b-6f572d1492a6.png)

It would be nice to add icons for these external links as we do for the Cowswap
![image](https://user-images.githubusercontent.com/70885163/153013210-9921fc72-7948-4241-be51-b5e9db4f7d1f.png)

There is no need to add a link 'View on Etherscan/Blockscount' to tokens) (discussed [here ](https://github.com/gnosis/gp-ui/pull/1011#issuecomment-1026798397))

**Comment by matextrem** [comment]
@elena-zh Do we need a design for this? 

Cc

CC: @alongoni

**Comment by elena-zh** [comment]
@matextrem , it is better to ask @alfetopito about this. 
Anyways, more details you can find in https://github.com/gnosis/gp-ui/pull/1011#issuecomment-1027126327

**Comment by elena-zh** [comment]
I have updated the issue description.
