### ISSUE TITLE
[2.6.0] Home button navigates to the Home page in Ethereum

### ISSUE THREAD

**Issue by elena-zh** [gnosis/gp-ui#1041]
1. Open the app
2. Switch to the Rinkeby network
3. Press on the Hove button

**AR**: Home page in Ethereum is opened

**ER**: Home page with respect of the selected network (Rinkeby) should be opened

**Comment by matextrem** [comment]
Hey @elena-zh, it seems it's working right now. Could you please test it ?

**Comment by elena-zh** [comment]
@matextrem , not working. 
The issue is still here: please, press not on the cow protocol logo, but on the 'Home' button: 
![image](https://user-images.githubusercontent.com/70885163/158342414-f0d9d583-cb19-46b9-b665-378cb0c4379a.png)
