### ISSUE TITLE
Add Batch Viewer to tx view

### ISSUE THREAD

**Issue by alongoni** [gnosis/gp-ui#1058]

**Comment by alongoni** [comment]
I've made a prototype for placing the access to the Batch Viewer in the Transactions Details page:
![image](https://user-images.githubusercontent.com/622217/156799376-9d1da7b3-9b4a-4638-8f27-fc4654eeb529.png)

Desktop version:
https://www.figma.com/proto/m7obOydxAhGNmlFYvxTk3Z/GP-Explorer?node-id=1719%3A2554&viewport=241%2C48%2C0.29&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1719%3A2554

Mobile version: 
https://www.figma.com/proto/m7obOydxAhGNmlFYvxTk3Z/GP-Explorer?node-id=1725%3A2648&viewport=241%2C48%2C0.29&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1725%3A2648

cc @elena-zh @henrypalacios

**Comment by elena-zh** [comment]
I'm still wondering: will we show some info in tooltips/near token icons in the batch viewer?
![image](https://user-images.githubusercontent.com/70885163/157442092-e4f545f8-75c3-44d6-af03-e672b3cf5a04.png)

**Comment by alongoni** [comment]
Hey @elena-zh. Surely yes, we still need to define which library will be used to represent the data.

**Comment by elena-zh** [comment]
Thank, @alongoni !
So as soon as we know the library, we will update the design file to see how it will look like. Correct?
