### ISSUE TITLE
Gnosis chain: Improve COW token name in order details + add token icon

### ISSUE THREAD

**Issue by elena-zh** [gnosis/gp-ui#1077]
Order details: https://explorer.cow.fi/gc/orders/0xf1b2178ce782b28f3701f9320095c65f794b9a1ef18806a7e5957b3802abcf80ff714b8b0e2700303ec912bd40496c3997ceea2b6242d0b1

**Steps**:
1. trade with COW token in Gnosis Chain
2. open order details page

**AR**: token name is `0x0000000000000000000000000000000000000000000000000000000000000020 (COW)`
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/5f54e44c-3e53-4f71-81b8-b75f4bb4baf7)

**ER**: token name is 'COW'
**Also, it would be great to add a token icon**

**Comment by alongoni** [comment]
hey @elena-zh I see the token name correctly:
![image](https://user-images.githubusercontent.com/622217/160608233-40fa8d30-3290-4b2a-a650-79afec978c95.png)

**Comment by elena-zh** [comment]
@alongoni , hm. Yes, me too now: strange things are happening. 
So I'm closing the task. Thank you!

**Comment by anxolin** [comment]
wow, that was weird....  i guess we will need to keep an eye if it happens again

**Comment by elena-zh** [comment]
Yes, I will track it
