### ISSUE TITLE
Guided tour

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-ui#12]
Originally from https://github.com/gnosis/gp-v1-ui/issues/1343

No longer applies to `dex-react` aka `gp-v1`, but can be considered for other apps

**Comment by anxolin** [comment]
Closing for now as part of a cleanup. We'll need to create a roadmap with all the prios, I've taken note of this in the list of specs https://docs.google.com/document/d/1ko1oDAECz3Oy1g0MxdrBzEuUsMhKcRHr8mMH-yTCzfs/edit 

Will likely reappear, but we'll need to setup some prios.
