### ISSUE TITLE
Adapt to OperatorAPI changes

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-ui#128]
See https://github.com/gnosis/gp-v2-services/pull/278

Main change is that we no longer need to deduce the `executedFeeAmount` from `executedSellAmount`.
We can instead use `executedSellAmountBeforeFees` directly.

**Comment by anxolin** [comment]
@alfetopito is this one still relevant?

**Comment by alfetopito** [comment]
Yes, that has not been done yet

**Comment by anxolin** [comment]
Aha, ok, sorry I tagged you while I was reviewing this with Anna, and I was not aware how important it was. I see now is not important, our numbers are correct, we just can use the new redundancy fields. 

I would leave this one for now unless we end up touching there and we want to go for it

**Comment by anxolin** [comment]
@alfetopito are we still interested in this one?

**Comment by alfetopito** [comment]
It's a tiny but irrelevant change.
I'd say no
