### ISSUE TITLE
Component: LimitOrder

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-ui#13]
Originally from https://github.com/gnosis/gp-v1-ui/issues/1381

Based on the existing `TradeWidget`, finish refactor and export it as `LimitOrder` component.

**Comment by anxolin** [comment]
Closing and taking note here https://docs.google.com/document/d/1vgRTY7IycHCeDfo-ytvG8a2AtZ-llqNbe-C6NEO0Rzk/edit#
