### ISSUE TITLE
TheGraph integration tasks

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-ui#15]
The Graph API:
https://thegraph.com/explorer/subgraph/gnosis/protocol-xdai
https://thegraph.com/explorer/subgraph/gnosis/protocol-rinkeby
https://thegraph.com/explorer/subgraph/gnosis/protocol

Some initial PR: Add apollo + Last Trades
gnosis/gp-v1-ui#1406

Some other **Pending Tasks** to research/implement:
* [ ] Add better support for typescript: Autogenerate?
* [ ] Add better parametrization of the widget
* [ ] Pagination?
* [ ] Subscriptions: Update automatically (change https for WS)
* [ ] Review if we want to implement more fined cache strategies

**Comment by alfetopito** [comment]
Damn! There's a transfer option! Will keep the original and close the copy

**Comment by alfetopito** [comment]
Also https://github.com/gnosis/gp-v1-ui/issues/1574 for xDai

**Comment by alfetopito** [comment]
I think this no longer applies, and it's not related to the explorer, but Mesa
