### ISSUE TITLE
Quick change networks menu

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-ui#160]
![image](https://user-images.githubusercontent.com/2352112/108105079-6eb4b100-708c-11eb-8b93-6b4ccd73195e.png)

* We would allow the user to change quickly from one network to the other using the header.
* We would respect the relative path when we do it
* This means that if I'm in rinkeby viewing one order ("/rinkeby/orders/1234"), and I navigate to  xDAI, it will redirect to the same page of the new network ("/xdai/orders/1234"). This way, if the order was not found because we are in the wrong network, we can easily find it in the right one!

**Comment by anxolin** [comment]
This one is still important

**Comment by alfetopito** [comment]
I remember talking about this with Protofire team, but couldn't find any issue. Guess this is the one :)

**Comment by elena-zh** [comment]
Hey @alfetopito , @anxolin , could you please clarify where we should redirect (404 page, search page/main page) a user when switch a network when a user are on: 
 - order details page
 - transaction details page

In most of cases there will no be matches for order ID/transaction hash for different networks..

Also, when a user is on 404 page and selects another network, is it OK to leave him on the 404 page, or navigate to the main page?

**Comment by alfetopito** [comment]
As we discussed during our sync, let's redirect the user to the landing page when switching networks.

That is, for details pages.
For list pages, it should remain in the same place

Example:
1. User is on order details for `mainnet` (https://gnosis-protocol.io/orders/0x.../) and selects `xdai` => go to `https://gnosis-protocol.io/xdai/`
2. User is on tx details for `rinkeby` (https://gnosis-protocol.io/rinkeby/tx/0x..../) and selects `mainnet` => go to `https://gnosis-protocol.io/`
3. User on address page on `xdai` (https://gnosis-protocol.io/xdai/address/0x...) and selects `rinkeby` => go to `https://gnosis-protocol.io/rinkeby/address/0x...`
