### ISSUE TITLE
[order details] Implement From link

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-ui#170]
From

- link component to User page (?)
- copy button

![screenshot_2021-02-18_07-37-48.png](https://images.zenhubusercontent.com/54161e1014b417b8716bc5ad/20f86267-ae39-42bc-88ed-693165aa0047)

**Comment by anxolin** [comment]
For now to Etherscan, later user address

**Comment by alfetopito** [comment]
Addressed on https://github.com/gnosis/gp-ui/pull/185 as a side effect

**Comment by alfetopito** [comment]
Done in #185
