### ISSUE TITLE
Account details: Last executed orders

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-ui#234]
- wireframes
- design
- implement: 
  - basic open account information page
  - Get last order: open + past orders
  - Table of latest orders
  - Paginate table
  - Make it responsive
  - Improve designs

**Comment by elena-zh** [comment]
Implemented: 
![image](https://user-images.githubusercontent.com/70885163/143249592-300dc32f-fe77-4318-b4d0-092ce3b4c26d.png)
