### ISSUE TITLE
Issue loader: Strange effect

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-ui#255]
If you load an order, periodically it checks for update

If you carefully watch the bottom of the page, you'll see a spinner appear and disappear creating a weird effect

**Comment by alfetopito** [comment]
Ah yes. This was intentional

#design-pending

xD

---

In summary, that's an indicator that the loading is happening on the background.
But at the time didn't really stop to think about making it look good.

@biocom can probably suggest a way to pass the message without looking so ugly?

**Comment by anxolin** [comment]
I suggest we can have a global flag for loading (global state), then we can represent that the app "is doing sth" anywhere we want. A swap UI might want to show it in the widget, and the explorer might want to show something in the footer for example.

I'm happy leaving this PR open if we just do a PR to kill that loading. We update periodically, but don't show a spinner.

**Comment by biocom** [comment]
If you want I can come up with a proposal for this. As you perhaps are suggesting @anxolin we could have a universal loader/status display. Or something else.

**Comment by alfetopito** [comment]
Disabling the loading for now https://github.com/gnosis/gp-ui/pull/281
