### ISSUE TITLE
Improve loading styles for order loader, order not found 404

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-ui#285]
![image](https://user-images.githubusercontent.com/2352112/110621655-c087bd00-819a-11eb-9e24-d4d50bf0a3a3.png)

![image](https://user-images.githubusercontent.com/2352112/110622065-44da4000-819b-11eb-849c-569fb8b6a584.png)

![image](https://user-images.githubusercontent.com/2352112/110622362-a6021380-819b-11eb-903f-13d83abe18a8.png)

It would be nice to revisit the styles of the loader and the 404s. 
I think they all have a similar issue.

The issues to address would be:
* The footer jumps from the top to the bottom
* They could have some nice HTML/CSS

i.e:
* **Not found order**: https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0xebea204089a9d5093a6bf56fb3005dc370f9a8e190eedf484dc9c1709d5f8d46424a46612794dbb8000194937834250dc723ffa56048a900a
* **Order Loading**: https://pr283--gpui.review.gnosisdev.com/storybook/?path=/story/orders-orderdetails--order-loading
* **404** https://protocol-explorer.dev.gnosisdev.com/whatever: 
* Also related to https://github.com/gnosis/gp-ui/issues/138 
* Also related to https://github.com/gnosis/gp-swap-ui/issues/339

If they need different solutions we can split this issue, but probably there's a share component that would help (like page component, or sth)

**Comment by anxolin** [comment]
Related to #138

**Comment by alongoni** [comment]
Here are some designs for: 
1. Loading order:
![UI_Explorer v1 -Loader](https://user-images.githubusercontent.com/622217/132564257-2c895f47-634e-4a38-9c38-7233734142aa.png)

2. Order not found:  (related to [#138](https://github.com/gnosis/gp-ui/issues/138#issuecomment-909614183))
![UI_Explorer v1 - Order not found](https://user-images.githubusercontent.com/622217/132564444-901b85a7-93df-4359-94bc-f004116626b5.png)

3. Page not found (404):
![UI_Explorer v1 - Not found 404](https://user-images.githubusercontent.com/622217/132564291-32d14470-c5fa-479b-814a-32eb99451979.png)

**Comment by alfetopito** [comment]
I'm happy with that.

cc @biocom for review
