### ISSUE TITLE
Explorer FROM should include the fee

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-ui#287]
Swap and explorer is not coherent

When we sell 100 DAI, then we and the fee is 35.3736 DAI as in the example below:

![image](https://user-images.githubusercontent.com/2352112/110953137-4f393d00-8347-11eb-9660-7cf610e8e07b.png)

We should show the FROM coherent in the explorer, this means to include the FEE in the FROM.

![image](https://user-images.githubusercontent.com/2352112/110953413-a0493100-8347-11eb-84e2-1cc4d472e9c5.png)

**Comment by alfetopito** [comment]
One concern that I have with this is, the prices won't match the from/to amounts.
Sure, you can see the exact sell amount on the `fill` row, but it looks odd.

I'll do this change anyway and we'll see what's the feedback.
