### ISSUE TITLE
Don't show the executed amount when the trade is 100% executed

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-ui#305]
![image.png](https://images.zenhubusercontent.com/5c4f7d89326c7a5e509d6165/3b0b1512-d603-4536-94b4-ed75405d3770)

Don't show the executed amount when the trade is 100% executed. It's redundant

**Comment by MareenG** [comment]
Additionally, it is wrongly displayed on mobile. I wasn't able to check properly on different devices but I did a quick check on my phone:  
![Screenshot_2021-03-17-11-44-02-880_com android chrome](https://user-images.githubusercontent.com/34510341/111456042-cdfef300-8716-11eb-9aec-71eb6f2e3a6d.jpg)

**Comment by MareenG** [comment]
I guess it fits here as well.
<img width="725" alt="Bildschirmfoto 2021-03-17 um 12 06 32" src="https://user-images.githubusercontent.com/34510341/111458208-7746e880-8719-11eb-8a51-b603c1b201e3.png">

**Comment by anxolin** [comment]
Good catch @MareenG, although I would say is best to open other issue for that. 

Probably we'll see a few issues in mobile, if there are too many, we try to accumulate in a PR, otherwise I would suggest to add one for fixing mobile for the "Filled" row
