### ISSUE TITLE
Entering Order ID with uppercase letters

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-ui#309]
# Description
Order is not found if the x in 0x is in upper cases

# To Reproduce:
Steps to reproduce the behaviour:
- If my recent activitiy is cleared in GP swap and want to trace a trade I will have to look for the order ID in Etherscan. 
-  Here the Order ID is in uppercase letters
1. Approach: Insert copied order ID and paste into explorer searchbar and add "0x"
a.) 0**x**804B97B985.... 
b.) 0**X**804B97B985....
2. Approach add it to the url: 
a) https://pr307--gpui.review.gnosisdev.com/rinkeby/orders/0**x**804B97B985....
b) https://pr307--gpui.review.gnosisdev.com/rinkeby/orders/0**X**804B97B985....

# Expected Behaviour
User gets directed to Order Details page

# Actual Behaviour
If the x is in lowercase the user gets directed to the order details page. 
If the user inserted an uppercase X the order is not found

# Screenshots/Videos
<img width="2010" alt="Bildschirmfoto 2021-03-16 um 11 41 04" src="https://user-images.githubusercontent.com/34510341/111296734-1a7dfc00-864d-11eb-829b-551fb68d8dbc.png">
<img width="2388" alt="Bildschirmfoto 2021-03-16 um 11 41 18" src="https://user-images.githubusercontent.com/34510341/111296767-25d12780-864d-11eb-97ec-1345a2da7620.png">

**Comment by anxolin** [comment]
Great catch!

**Comment by anxolin** [comment]
@MareenG I move this one to QA if you want to test if Leandro PR fixes the issue. 

Note that he references this issue in his PR, and this automatically adds into the timeline of this issue the link to the PR.
In the PR you can find the instructions and the link #323

**Comment by MareenG** [comment]
I still encounter some issues for the x in 0x . 
If I add it in uppercases in the searchbar it looks like it gets stuck. The id is recognized but the details page is not loading. 
The loading icon flickers and doesn't spin.


https://user-images.githubusercontent.com/34510341/112308117-12a00680-8ca2-11eb-9aa7-023cb940c69b.mov


If I add it into the URL with an upper X in the 0x it also doesn't load. However, If I load it with an lowercase x and then ad the X it loads...


https://user-images.githubusercontent.com/34510341/112308156-1df33200-8ca2-11eb-89b1-dcd3c3b24ce6.mov

The other characters work no matter if they are in lower, upercase or mixed

**Comment by alfetopito** [comment]
Lol, that's weird. I'll try to reproduce it

**Comment by alfetopito** [comment]
@MareenG I could not reproduce, but I've made a few more changes.
Could you try again?

**Comment by MareenG** [comment]
Yeah, it was odd that the id got recognized but then it got stuck. 
I tested it again and today it worked :)

**Comment by anxolin** [comment]
@MareenG are you sure you are testing in the right place? 
I tested before Leando did the last changes and it was also working for me. 

Note you reported this bug and pasted some links from a **frozen version**, however, when we do any code change, we do it in a PR, in this case #323 
Each PR has its own URL, u can always find it as a comment in the PR, so for example this issue should be tested in the PR and not in the frozen version.

**Comment by MareenG** [comment]
I used https://pr323--gpui.review.gnosisdev.com/ from the PR. Was this the correct URL?

**Comment by anxolin** [comment]
> I used https://pr323--gpui.review.gnosisdev.com/ from the PR. Was this the correct URL?

Yes, that's the one
