### ISSUE TITLE
Suggestion: ? icon for Status

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-ui#310]
At the moment you can't cancel orders might be good to delete it here until we have it implemented

<img width="360" alt="Bildschirmfoto 2021-03-16 um 13 15 17" src="https://user-images.githubusercontent.com/34510341/111307433-bc0b4a80-8659-11eb-9b68-055d7c06f59e.png">

**Comment by anxolin** [comment]
I think is not worth it. We will add cancelation asap

**Comment by anxolin** [comment]
Let me know if u want to keep this one open

**Comment by MareenG** [comment]
Can be closed :)
