### ISSUE TITLE
Suggestions: Order not found 

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-ui#313]
From a user perspective it might be got to know if my ID is invalid or incorrect ( too short, too long, etc.)

The display **Order not found** is quite tiny and depending on the screen size really hard to read. Might be good to change the font size.

<img width="1170" alt="Bildschirmfoto 2021-03-17 um 11 14 28" src="https://user-images.githubusercontent.com/34510341/111451883-34354700-8712-11eb-8cd6-23db3398f59c.png">

**Comment by anxolin** [comment]
Slightly related to https://github.com/gnosis/gp-ui/issues/285

**Comment by anxolin** [comment]
@alfetopito maybe something for Protofire

**Comment by elena-zh** [comment]
Fixed in #658
