### ISSUE TITLE
Transaction deadline

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-ui#315]
The expiration deadline ends always a few seconds before the set transaction deadline

<img width="603" alt="Bildschirmfoto 2021-03-17 um 12 53 06" src="https://user-images.githubusercontent.com/34510341/111463420-d9a2e780-871f-11eb-9910-49480f5908b6.png">
<img width="275" alt="Bildschirmfoto 2021-03-17 um 12 54 55" src="https://user-images.githubusercontent.com/34510341/111463634-15d64800-8720-11eb-8411-5b15f0a39d57.png">
<img width="275" alt="Bildschirmfoto 2021-03-17 um 12 55 23" src="https://user-images.githubusercontent.com/34510341/111463649-1969cf00-8720-11eb-84e4-bb5f23cef222.png">

**Comment by alfetopito** [comment]
I don't get it. What was the value you were expecting to have?

Or do you mean, `creation time - expiration time` not exactly equal to (for example) 20 min?

**Comment by MareenG** [comment]
Yes, it is a bit picky but it is always like 19min and 56 sec. For short deadlines this doesn't really have an impact but the greater the value for transaction deadline is the less accurate is the value gets.

**Comment by alfetopito** [comment]
That has a simple explanation.

The `validTo` time is calculated when you place the order on the client side, based on local time + time offset (defaults to 20min)
That information is sent to the wallet to be signed, and after that sent to the backend.
Only then the creation date is set (when the backend receives it).

So, the time difference will depend on:
1. How fast your wallet opens the signature window
2. How long you take to sign it
3. How long until the order reaches the backend

You can try to experiment waiting longer to sign just to validate.
One test case could be:
1. Set expiration to the minimum possible (1min)
2. Place the order on the UI
3. On the wallet signature modal, wait 1 min, then sign it

- Should the order placement fail? I'm not sure. Will have to test/ask backend what would happen.

**Comment by MareenG** [comment]
Thank you for explaining this. I will look a bit deeper into it and try the approach you mentioned :)

**Comment by anxolin** [comment]
@MareenG let us know if we need to look into sth or we can close this one.

**Comment by MareenG** [comment]
I played around with this yesterday and I came across one question. So If I understand it correctly the transaction deadline starts once I click CONFIRM SWAP. However, the order is placed once you sign the transaction. If I have short transaction deadlines (1min) and I need too long to sign the transaction your transaction period is shortend by the time span you need until you sign it. 
Wouldn't it be better to start the transaction period after signing it with MetaMask or any other wallet and not once you click CONFIRM SWAP?

**Comment by alfetopito** [comment]
> Wouldn't it be better to start the transaction period after signing it with MetaMask or any other wallet

Correct me if I'm wrong @anxolin, but I don't think that's possible.
What we send to the wallet cannot be updated by the wallet.

In case you take longer than your deadline to sign/submit your order to the backend it'll just fail straight away.

@fleupold @nlordell any insights from the backend point of view regarding this?

**Comment by anxolin** [comment]
What Leandro said above. Mareen, u are in a catch-22, u want the signing window to update after you sign, but the date is part of what u sign 🔁

**Comment by nlordell** [comment]
Correct, the expiry date is part of the order that is being signed, so it has to be fixed to some value before requesting a signature from MetaMask/user.

**Comment by MareenG** [comment]
Thank you got it, sorry for making such a big discussion out of it.
