### ISSUE TITLE
Gnosis COW Welcome Screen 

### ISSUE THREAD

**Issue by annamsgeorge** [gnosis/gp-ui#325]
Welcome Screen when loading CowSwap: 
(Not related to the "About Section") 

- Small window popping up
- Background is blurred out

The window shows: 
- our COW logo 
- below the words "Coincidence Of Wants" (highlighting the first letter of each word C - O - W) 
- below the words "COW Swap" 
- below in small letters the words (in grey) "don't show again". If this is clicked, the pop up window disappears and the user proceeds to the website. When visiting again the pop up screen will not be shown to him anymore. 
- in the top right (in grey color) there is an x to close the window and proceed to the website. If this is clicked, the window will pop up again at next visit 

Effect: The words are one after another slided in from the right. 

Visualization example: ![Screenshot 2021-03-24 at 09.34.47.png](https://images.zenhubusercontent.com/6059d7cca7474e5d8699f72c/cb39a47c-68c8-43f4-bd3b-5a00efa3e225) 

Behaviour:
- When opening the website, the welcome screen pops up automatically 
- The words are sliding in within a 2 second window (approximately)
- The user can either close the window on the top right by clicking on x . The user proceeds to the website. The user will see this pop up window again on next visit. 
- Or the user can click on the words "don't show again". The user proceeds to the website. The user will never see this pop up screen again on future visits.

**Comment by anxolin** [comment]
Thanks for the detailed spec

**Comment by anxolin** [comment]
As discussed with @annamsgeorge this one gets deprioritized. cc: @biocom

**Comment by biocom** [comment]
@annamsgeorge While this is de-prioritized, just wanted to add on:
> The user can either close the window on the top right by clicking on x . The user proceeds to the website. The user will see this pop up window again on next visit.

In my opinion I think it's better to only show this once: If the user clicks on the X or outside the modal it should close and never be shown again. The main reason being annoyance of being bothered by a perceived 'pop-up'.

Curious on your thoughts.

**Comment by annamsgeorge** [comment]
fully agree @biocom 
One option could also be to give a check box "don't show again". Maybe the user just doesn't want to raed this time and therefore closes it, but would like to have the option to see it in the future. 
However, if we keep the About section, then there is no need for this box. We can simply only show it once.

**Comment by anxolin** [comment]
Closing this one since we will probably do a landing instead. Feel free to reopen if still relevant
