### ISSUE TITLE
Access only via Invite Password

### ISSUE THREAD

**Issue by annamsgeorge** [gnosis/gp-ui#326]
Example of another company requiring an invite code for early access:
https://www.unslashed.finance/ 

Their flow: (which I would not recommend, proposal for our solution below) 
- User visits landing page. 
- On the top right is a button "Get Early Access"
- The app opens, requesting you to confirm access with your Wallet account first 
- Once you have connected your wallet, a window pops up asking the user for an invite code. 

How it looks: 
![Screenshot 2021-03-24 at 09.50.42.png](https://images.zenhubusercontent.com/6059d7cca7474e5d8699f72c/2d344e21-9e6f-4889-8f94-037856028971)

- The user then proceeds to a public channel of Unslashed Protocol (for example Telegram: https://t.me/UnslashedFinance) and informally asks for an invite code there. Some of the members will then send you an invite code via DM. 
- The user then returns to the website and pastes in the invite code. 
- Now the user has full access to the app 

Note:
- Each invite code only works one time
- The invite code is connected to the wallet account you are connected with. 

How our flow could look like:
- When the user tries to open the app a window pops up asking the user for an invite code. This window includes direct links to our Telegram and Discord 
- We could have a message pinned to the Discord channel / Telegram channel stating "type "/invite code" to receive an invite code to Cowtrade(emoji link)." 
- When the user writes this command, he privately receives an invite code automatically
- Rather than tied to the users wallet account (like it seems to be the case for unslashed protocol??), the password protection is done via the chrome browser. The reason being that users don't want to connect their wallet before seeing the app itself. 
- The code enables the front end. 
- The backend is accessible without password 

Questions: 
- Do this services provide stats?: I think google analytics could provide stats here although we would have to check about gdpr. 
- Do we care if someone reuse the code? can it be avoided?:  every code can only be used once. 
- Will this service give u the feature, to allow someone to share with 5 people. Or do we want this feature or is just a ondemand thing? - i think the idea is for people to join the channel, it literally takes 5 seconds. I like this idea though, we could also say that every code can be used up to 5 times. Then the user can share their code with friends. 
- any legal concern? we should double check with them: will double check with them!

**Comment by annamsgeorge** [comment]
Proposal for Invite Screen: 
<img width="775" alt="Screenshot 2021-03-24 at 17 54 44" src="https://user-images.githubusercontent.com/33424780/112388868-178da600-8cf4-11eb-9565-d5f309b47549.png">

**Comment by anxolin** [comment]
Doesn't apply anymore
