### ISSUE TITLE
The surplus is incorrect for buy orders

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-ui#330]
![image](https://user-images.githubusercontent.com/2352112/112599089-ba871280-8e0f-11eb-815e-44bddfff8ff0.png)

In the example, we have a good surplus, but it doesn't show.

**Comment by anxolin** [comment]
Closed for duplication with #346

**Comment by anxolin** [comment]
Reopening, cause https://github.com/gnosis/gp-swap-ui/issues/346 was in the wrong project 🐮

Keeping this one.


Adding @alfetopito comment:
> I feel like this order should have some surplus, given the difference between limit and execution prices, but it doesn't.
https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0xfb2b969bf74fc47bc1b03c6a934f138d42637e663c458c601addb480c5c1c5a55b0abe214ab7875562adee331deff0fe1912fe42605d00aa

> Guess the issue is how we calculate surplus for buy orders.
Another one with the same problem https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0x8bd5855c020959cf31fd90271de0c35dfca80382704cb43124743330622aa7635b0abe214ab7875562adee331deff0fe1912fe42605d0251


Yes, I believe is because surplus in buy orders means that you pay less from your FROM tokens. So the price is smaller instead of higher. Instead of a `surplus` is kind of an `surminus`, `underplus`, ... 😆

If theres a surplus function, and we flip the two prices we give it for buy orders, Im sure we get the right number.

**Comment by alfetopito** [comment]
> Reopening, cause gnosis/gp-swap-ui#346 was in the wrong project cow

I could swear I migrated it to this repo... :shrug:
