### ISSUE TITLE
Rephrase "GP+Gas fee" and related hover text

### ISSUE THREAD

**Issue by annamsgeorge** [gnosis/gp-ui#335]
![Screenshot 2021-03-26 at 10.16.31.png](https://images.zenhubusercontent.com/6059d7cca7474e5d8699f72c/95b80fe7-24f0-4943-8393-b279d01925c6)

It's not clear to users what "GP" means in the context of CowSwap. 

to do: 
1) Rephrase "GP/Gas Fee" to: "Protocol/Gas fee"
2) Replace hover text with: "All fees (incl. gas fees) are already included in your receiving balance. You don't need ETH for this trade."

**Comment by MareenG** [comment]
I also feel that it is not that clear, that the Fee is deducted from the amount you insert in the FROM section. 
I think this should be made a bit more obvious, especially for small volume trades the fee eats a lot of the tokens.

**Comment by anxolin** [comment]
@W3stside is already addressing this in here https://github.com/gnosis/gp-ui/issues/314

Also, please note that this Github repo is only for the Explorer, not for the Swap UI. In this case, I will close this issue for duplication, but in other case, if we create it in the wrong project we can always move transfer the issue. There's a link in the bottom right part of Github. 
![image](https://user-images.githubusercontent.com/2352112/113190666-de59b680-925c-11eb-8510-670eaebb0dbe.png)
