### ISSUE TITLE
Failed to fetch notification

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-ui#347]
I got the following message below the order details
<img width="779" alt="Bildschirmfoto 2021-03-30 um 10 31 28" src="https://user-images.githubusercontent.com/34510341/112958972-4025fd80-9143-11eb-9371-d72da36b13bc.png">

It appears and disappears. After refreshing the website only the error message was shown

**Comment by MareenG** [comment]
I also got several failed to fetch notifications for Cowswap today( between 10 and 11am). Now they seem to be resolved

**Comment by alfetopito** [comment]
That is a generic error message that we display when we fail to fetch the order details from the backend.
You see it appearing and disappearing because while an order is not expired, the UI will keep updating the order details in the background to check whether it has been executed without the need to refresh the page.
And since it was failing, the error message was displayed.

There are already pending issues to better handle the error message.

Regarding the issue, might have been an sporadic network or backend failure. Can't tell at this point.

**Comment by anxolin** [comment]
There might be also a technical reason to see this non informative message.

details: This is also likely related to one issue @vkgnosis discovered today. When the ther backend returns an Error, it's sometimes not returning the CORS headers, this makes the actual request to fail, so even if it's a controlled and nice typed error, the FE will see it as a failed fetch request.

**Comment by anxolin** [comment]
Linking this to this related issue https://github.com/gnosis/gp-swap-ui/issues/339

**Comment by elena-zh** [comment]
In order to reproduce this issue: 
1. Create an order
2. While the order is in the 'Open' status, open the order details in the Explorer
3. Switch off the internet connection
![image](https://user-images.githubusercontent.com/70885163/135876404-44cccc9f-962a-44fc-9a5e-7c06fd651a46.png)

**Comment by alfetopito** [comment]
@alongoni @fapesteguia @maria-vslvn this would be a nice issue to tackle next.

**Comment by alongoni** [comment]
Perhaps using toast notifications would be a good idea?
![UI_Explorer v1  - order detail page _ failed to fetch order notification](https://user-images.githubusercontent.com/622217/135930353-f5e231b1-499f-491d-b24c-ac47f924a0d5.png)
Like https://www.npmjs.com/package/react-toastify
cc @alfetopito

**Comment by alfetopito** [comment]
Yes, that's one idea we discussed earlier.

What do you think regarding that kind of UX @biocom @anxolin

**Comment by biocom** [comment]
I see different objectives

1. User is offline > can't fetch order
2. A specific error occurred fetching an order

For both objectives I regard a toast notification inappropriate for the purpose it intends to serve. A toast notification IMO should be shown after an explicit user initiate action (e.g. you submitted an order -> getting feedback from a toast notification or an order gets settled, etc.).

Instead
1. I think we should show a 'You're offline' banner on top.
2. Show an error banner more close to the table or somewhere below the page header.

The offline banner (point 1 above) could also be shown just like point 2.

**Comment by alfetopito** [comment]
I'm wondering now about this.

The UI is still functional, you can still see everything about your order.
There's only no background update. Or one update failed. A page refresh "should" be enough to fix, if needed.

What if we don't say anything at all for this type of error?

Of if we do, something like point `2` with a subtle error message like  "background update failed, refresh to see new stuff"

**Comment by alongoni** [comment]
> I'm wondering now about this.
> 
> The UI is still functional, you can still see everything about your order. There's only no background update. Or one update failed. A page refresh "should" be enough to fix, if needed.
> 
> What if we don't say anything at all for this type of error?
> 
> Of if we do, something like point `2` with a subtle error message like "background update failed, refresh to see new stuff"

hey @alfetopito, something like this?

![UI_Explorer v1  - order detail page _ failed to fetch order notification](https://user-images.githubusercontent.com/622217/136103228-9ead6f0a-4fa7-4885-b1f5-f83e99bf647f.png)

**Comment by alfetopito** [comment]
Yes, that is more subtle.

@biocom good with you?

**Comment by alongoni** [comment]
Design updated:

Warning:
![UI_Explorer v1  - order detail page _ failed to fetch order notification](https://user-images.githubusercontent.com/622217/136465632-d9602adb-33d8-42b4-932c-e32b73fcd3b7.png)

Error:
![UI_Explorer v1  - order detail page _ failed to fetch order notification-1](https://user-images.githubusercontent.com/622217/136465629-d15769d5-9334-46b3-af78-4cd58a98abeb.png)

**Comment by alongoni** [comment]
Design updated:
- text align to left.
- add "try again" link.
![UI_Explorer v1  - order detail page _ failed to fetch order notification](https://user-images.githubusercontent.com/622217/136964814-ce0a029e-c53b-4dcb-a7c6-15b675ea3613.png)
![UI_Explorer v1  - order detail page _ failed to fetch order notification-1](https://user-images.githubusercontent.com/622217/136964804-de670815-6d95-4927-a53d-9f38d4243d0b.png)

**Comment by fapesteguia** [comment]
@maria-vslvn Can you handle this issue?

**Comment by elena-zh** [comment]
The issue is a WIP in #992 pr
