### ISSUE TITLE
Order not loading

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-ui#361]
Sometimes, the order will stay loading forever.
Happened to Felix and I today during the trade challenge.

Not sure anymore, but I think this was my order that wouldn't load https://protocol-explorer.dev.gnosisdev.com/xdai/orders/0xc7f192c3366df3a42c5c591f6f7df453e3f5aa047659703546ab7b14e778dd19fe4449f4d9ed14df3acd74bba6dcb038d3f7a1cb60705dc4

Opened the same link in another browser and it loaded fine.

**Comment by anxolin** [comment]
It would be good to review the network and console in case this happens. Could it just be that the API was down or something?

**Comment by alfetopito** [comment]
I remembered checking and apparently the order was loaded, but the UI got stuck in a state that didn't show it.
I could see the requests being fulfilled in the console logs.

Did not get to debug further at the time given that it was in the middle of the trading challenge

**Comment by anxolin** [comment]
okok, let's keep an eye on this then. I never experience this before.

**Comment by anxolin** [comment]
@alfetopito I'll close this one. I think it was because the environments DEV/STAGING don't share data, and there was a mismatch in the API and explorer that we were using between explorer and cowswap. Not should be fixed.


Pls, reopen if it's not this, or is not the case
