### ISSUE TITLE
Use production endponts for the API

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-ui#374]
> Sister task of https://github.com/gnosis/gp-swap-ui/issues/422

The backend has just setup the environment for production:
*  https://protocol-mainnet.gnosis.io/api
*  https://protocol-xdai.gnosis.io/api
*  https://protocol-rinkeby.gnosis.io/api

We should make sure that:
* In production and staging (tags, master, and releae/xxxxx  branches) we use the production endpoints for the API
* In PRauls and in develop, we use develop endpoints

**Comment by anxolin** [comment]
Related to https://github.com/gnosis/gp-swap-ui/issues/421

**Comment by alfetopito** [comment]
I'm seeing a problem with this:

> In PRauls and in develop, we use develop endpoints

The db is not shared between prod/dev. Example:

- Prod rinkeby: https://protocol-rinkeby.gnosis.io/api/v1/orders/0xecc7a0dd84b7a41d953231f5d04f9e8141014e212d2f855c3e46a02bccb0bed95b0abe214ab7875562adee331deff0fe1912fe42607db33b
- Staging (dev) rinkeby: https://protocol-rinkeby.dev.gnosisdev.com/api/v1/orders/0xecc7a0dd84b7a41d953231f5d04f9e8141014e212d2f855c3e46a02bccb0bed95b0abe214ab7875562adee331deff0fe1912fe42607db33b

My concern is that there will be no way to use dev/PRs for testing prod issues going forward.
The only alternative will be to start a local server with prod endpoints.

---

Well, that actually makes sense.
Just have to keep in mind both environments are isolated from each other.

**Comment by anxolin** [comment]
Yes, for now this is true. I think in the future, each API will reconstruct the data from events if I understood correctly

Also, this is why Cow Swap and Explorer have a similar logic in terms of the API they use depending on the environment. 
Cow Swap will decide if it needs PROD/DEV, and will use that for both the explorer and the API. This way, it will be coherent
