### ISSUE TITLE
Transaction link: Etherscan

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-ui#375]
**Description**
Include link to Etherscan in the order details. 

**Describe the solution you'd like**
For now, Cow Swap only creates fill or kill orders. For this orders, when they are executed, they will have a single associated transaction (settlement). 

It would be nice to add the link to Etherscan in the order details. 

Orders with multiple trades can potentially have multiple ethereum tx hashes. This is why the link will be added in the "Fills tab instead" (https://github.com/gnosis/gp-ui/issues/247)

**Additional context**
Implemented in the backend: https://github.com/gnosis/gp-v2-services/issues/334#issuecomment-800027727

**Comment by alfetopito** [comment]
I was sure we had an issue for this already...
But I can't find it.
Anyway, we'll need to query another endpoint to get this data, as it's not included in the order details response
