### ISSUE TITLE
Settings is a bit hidden

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-ui#377]
Some users don't find the settings. 

Is there a way to make it more visible?

![image](https://user-images.githubusercontent.com/2352112/114862243-91deb100-9dee-11eb-8e27-f2bebcd93141.png)

Also, related good to do together https://github.com/gnosis/gp-swap-ui/issues/402

**Comment by anxolin** [comment]
cc/ @biocom

**Comment by biocom** [comment]
I'd simply add the text link next to the wrench icon 'Settings'. Can create a PR for it.

**Comment by anxolin** [comment]
Oka, sounds good!
