### ISSUE TITLE
Inconsitent use of decimal comma/point

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-ui#382]
**Describe the bug**
In some cases we use the Decimal comma in others we use the point.

**How to Reproduce**
1. to a trade on CowSwap
2. Observe in the Explorer

**Expected behavior**
Use , or . 
**Screenshots**
<img width="1142" alt="Bildschirmfoto 2021-04-16 um 11 08 30" src="https://user-images.githubusercontent.com/34510341/115002094-a2e9f980-9ea4-11eb-96db-6f4c4712d7e8.png">

I

**Comment by alfetopito** [comment]
Yep, something is wrong there.
I think the is that in some places we use local aware formatting, which might use `,` as decimal separator and `.` as thousands separator.

**Comment by MareenG** [comment]
It happens also within the some category field. If I change the way the price is displayed it switches from , to . 

<img width="482" alt="Bildschirmfoto 2021-04-28 um 11 03 25" src="https://user-images.githubusercontent.com/34510341/116377530-93a66c80-a811-11eb-9493-b614fdb77997.png">
<img width="490" alt="Bildschirmfoto 2021-04-28 um 11 03 18" src="https://user-images.githubusercontent.com/34510341/116377539-94d79980-a811-11eb-9e5f-3d077ee5c59e.png">
