### ISSUE TITLE
Etherscan link is not shown automatically

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-ui#407]
**Describe the bug**
User needs to refresh to see the etherscan link

**How to Reproduce**

1. Trade in cowswap
2. Open explorer while the order is OPEN
3. Wait until the trade is executed
4. Verify if the link is displayed automatically

**Expected behavior**
User sees the link to etherscan without needing to refresh

**Additional context**
Found by our QA expert @MareenG https://github.com/gnosis/gp-ui/pull/404#pullrequestreview-645573171

**Comment by alfetopito** [comment]
Ahhhhh... my fault of course. Missed that.

**Comment by anxolin** [comment]
Fault of the reviewers!
