### ISSUE TITLE
Contracts for the explorer are not network aware

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-ui#408]
**Describe the bug**
The explorer has support for mainnnet, but also for rinkeby and xdai. However the footer links only point to mainnet

**How to Reproduce**
1. Go to http://protocol-explorer.dev.gnosisdev.com/rinkeby (note the rinkeby at the end)
2. Click on the footer link
3. If they take you to the version in mainet or rinkeby/xdai

**Screenshots**
![image](https://user-images.githubusercontent.com/2352112/116221648-18c84d80-a74e-11eb-8ef3-ec7ed80f0107.png)

**Comment by elena-zh** [comment]
Still valid

**Comment by anxolin** [comment]
This should be a quick fix, specially since we already do it in CowSwap. Low prio though
 cc/ @alfetopito

**Comment by anxolin** [comment]
Easy to test with the fancy new network switcher :)
