### ISSUE TITLE
[v2] Generic tabs

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-ui#41]
* [ ] Review the tabs components and make sure we have a simple dumb tabs component
![image](https://user-images.githubusercontent.com/2352112/103770274-04890500-5026-11eb-824e-7229cd42ee73.png)
* [ ] src/components/common/Tabs

**Comment by biocom** [comment]
Just as a note (but you may already be aware): Tabs component also in use for [Orderbook / Trades] and [Price Chart / Depth Chart]
