### ISSUE TITLE
Token name and logo not recognized (xDai)

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-ui#412]
**Describe the bug**
The 1Inch token is not recognized in the Explorer. Only the address is shown. 

**How to Reproduce**
1. Go to CowSwap and trade 1Inch on Xdai
2.  Observe trade in Explorer

**Expected behavior**
Logo and Name should appear for the 1Inch token

**Screenshots**
<img width="954" alt="Bildschirmfoto 2021-04-28 um 12 35 57" src="https://user-images.githubusercontent.com/34510341/116390968-e33f6500-a81e-11eb-8909-a8900af423c2.png">

https://gnosis-protocol.io/xdai/orders/0xeaf0e17c523f8789f1aca89862053a1f945bfa08cfc02fa74a09aade9d844c938bc0fe84022542e1611ff252090028df741ad67060893ccb

**Comment by alfetopito** [comment]
Funny thing, it loaded for me 
![screenshot_2021-04-28_09-39-19](https://user-images.githubusercontent.com/43217/116440687-93a06f80-a805-11eb-992d-8752d12328ef.png)

My guess: the call to fetch token details failed. The fallback is to show only the address.

Can you see the token details after a refresh?

**Comment by alfetopito** [comment]
And also, here there's a huge different between the amount precisions for you and me.

Will increase the priority on https://github.com/gnosis/gp-ui/issues/382

**Comment by MareenG** [comment]
Now the name and logo are displayed. Also for new trades. 
I tired refreshing yesterday but it still didn't load.

**Comment by anxolin** [comment]
Closing for now. It could have been a temporal error. We can reopen if it happens again
