### ISSUE TITLE
Represent the route execution of the order

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-ui#458]
**Description**
We all love the Explorer, and their order/trade details, however, some users expressed their wish to see how much of the trade is a COW, and how much was traded in each AMM.

This can be partially seen from Etherscan, although is a bit hard to read, specially because the same settlement tx includes all the trades for that block. 

**Proposal**
It would be great to see a detail of the actual execution paths for a single order.

**Context**
User feedback:

> Would be cool to have a rundown of what happened in a transaction made through cowswap - prompt on a side showing how the funds were handled (I know there's Etherscan for it but would be a plus to show in a more ergonomic way if X% was done in P2P, X% through UNI X% through some other dex etc)

**Comment by alfetopito** [comment]
Do we have that data available anywhere? I mean, besides etherscan.

**Comment by anxolin** [comment]
No yet. This is a wish request, but these info is not available right now (at least in a simple way to consume)

**Comment by elena-zh** [comment]
Hey @alfetopito , is this ticket related to #780 ?

**Comment by alfetopito** [comment]
> Hey @alfetopito , is this ticket related to #780 ?

Yes!

**Comment by elena-zh** [comment]
@alfetopito , then, can we close this issue in order not to have duplicates on the board?

**Comment by alfetopito** [comment]
> @alfetopito , then, can we close this issue in order not to have duplicates on the board?

Yes!
