### ISSUE TITLE
Smart contract wallet integration: Signing

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-ui#49]
> Part of https://github.com/gnosis/gp-ui/issues/55

Review how this could look like, the requirements, dependencies. 
* How does it look for Gnosis Safe?
* How does it look for other smart contract wallets?
* If it's easy, jump to implementation. If not, let discuss what needs to be done

https://docs.google.com/document/d/1Nd2Vx9ZTWZONim2rsHEWepcLIlKmJ10cKbcdaDk-ejI/edit#heading=h.wdk3uhghiufx

**Comment by elena-zh** [comment]
Seems that it is already implemented in #826
