### ISSUE TITLE
Show timezone on dates

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-ui#613]
**Description**

Show timezone on dates

**Proposal**

Small suggestion for the protocol explorer. I think it might be beneficial to show the timezone in the order details page for the (Submission|Expiration) Time fields. While the (?) tooltip mentions that its converted to local time based on your browser settings, I still think it would be helpful to display what those settings actually are.

**Additional context**

Suggested by @nlordell on slack

**Comment by matextrem** [comment]
@alfetopito How do you want the timezone to be shown ? Something like `America/Los_Angeles` or `GMT-0700`

**Comment by alfetopito** [comment]
I prefer the time (`UTC+0100`), as timezone "names" are ambiguous.

@nlordell @anxolin any thoughts?

**Comment by anxolin** [comment]
No preference, timezone are something that are not in the mind of the users. I would think they expect us to show local times. 
But i have no idea if adding timezones or tame offsets is something people will like. 

Other option is adding nothing, showing local time, and on click it shows UTC time



**5 months ago (05/04/2021 9:04:56 AM)**  ----->  **5 months ago (05/04/2021 8:04:56 AM, GMT+1)**

> I prefer the time (UTC+0100), as timezone "names" are ambiguous.

Fine with me, no strong preference. Only thing, if u go for offset, i personally like `UTC+1` better than `UTC+0100`

**Comment by alfetopito** [comment]
> > I prefer the time (UTC+0100), as timezone "names" are ambiguous.
> 
> Fine with me, no strong preference. Only thing, if u go for offset, i personally like `UTC+1` better than `UTC+0100`

How should we treat timezones that have minutes increments?

https://en.wikipedia.org/wiki/List_of_UTC_time_offsets
![screenshot_2021-09-21_11-52-48](https://user-images.githubusercontent.com/43217/134230256-6b5bbbca-7d3c-49d9-b9e8-123afb8baeab.png)

`UTC+1:45` ?

**Comment by anxolin** [comment]
> How should we treat timezones that have minutes increments?

What a weird thing to do, minute offsets, just to mess with people minds :) 
anyways, UTC+01:45 is also fine. I guess mainly the missing `:` was what was bothering me.
