### ISSUE TITLE
Implement: Design hard error handling

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-ui#632]
# Summary

Similar to how hard failures are handled on CowSwap, design a page for hard errors on Explorer

Design:
https://github.com/gnosis/gp-ui/issues/138#issuecomment-916048583
---

My bad, I'm expanding the task scope.
We can handle the hard errors in another task.

_Originally posted by @alfetopito in https://github.com/gnosis/gp-ui/issues/138#issuecomment-912022163_

**Comment by elena-zh** [comment]
Still valid.

**Comment by elena-zh** [comment]
Also, it would be nice to show a loading error for this case: 
![image](https://user-images.githubusercontent.com/70885163/145788915-823c8d4f-ef0f-4a7f-8972-578493c6c95c.png)

**Comment by alfetopito** [comment]
Hmm, I'm more interest in how you managed to get those errors :sweat_smile: 
Was backend down?

But indeed, we should have the error handling on this page as well.
Wasn't that added by @alongoni to the other pages already? Or was it only the design?

**Comment by elena-zh** [comment]
> Hmm, I'm more interest in how you managed to get those errors 😅
> Was backend down?

@alfetopito , I just left the tab opened for a weekend. And on Monday I faced this. 
Those errors were running until I reloaded the page.
