### ISSUE TITLE
Implement order not found design/behaviour

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-ui#641]
# Summary

Implement  the error handling designed on https://github.com/gnosis/gp-ui/issues/138

See #138 for more details

Context:
---

> @alfetopito How many errors are we handle?
> I've added a details box for errors.
> ![UI_Explorer v1 - No result-box](https://user-images.githubusercontent.com/622217/131719196-a0126591-2d57-4957-9bac-6933d5a585eb.png)

Not quite what I had in mind.
It thought something like the hard error handler on CowSwap.

But thinking about it again, your proposal does make sense.
It allows users to search for it again. Maybe there was a type on the order id.
And has the context in case users want to reach out for help.

Looks good to me. I'll ping @biocom again for input :)

_Originally posted by @alfetopito in https://github.com/gnosis/gp-ui/issues/138#issuecomment-910715207_

**Comment by biocom** [comment]
Some notes:
- Can highlight the individual errors, like you would see in your console.log (X icon and red background).

Just so the error visually stands out from the rest of the elements on page.
