### ISSUE TITLE
xDai data not loading

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-ui#685]
# Summary

Investigate/fix issue loading onchain data on xDai network

----

I could swear I tested xdai and it worked fine a few days ago.
Tried now and indeed, not loading.
My guess is that there's an issue with the xdai rpc connection, as the token info is fetched from the chain.

Should be a separated task, though

_Originally posted by @alfetopito in https://github.com/gnosis/gp-ui/issues/661#issuecomment-925305211_

## To test
- Go to https://pr611--gpui.review.gnosisdev.com/xdai/address/0xFF714b8b0e2700303eC912BD40496C3997ceEa2b/

**Comment by henrypalacios** [comment]
@alfetopito @elena-zh 
After a few attempts to look for the bug, I started to notice that the token reading was working, I think it has something to do with the XDAI RPC connection. 
![Selection_293](https://user-images.githubusercontent.com/4270166/134517245-b107f400-bf8d-4260-aca2-90958140eff7.png)
