### ISSUE TITLE
[2.4.0] Order appears in 'Signing' status when cancel trasaction

### ISSUE THREAD

**Issue by elena-zh** [gnosis/gp-ui#844]
1. Connect the Cowswap with a Gnosis safe
2. Specify tokens to Sell/Buy in the Swap form
3. Press on the Swap, confirm in the modal
4. In the Safe Cancel transaction signing

**AR**: Order appears in 'Signing' status in Explorer
https://watch.screencastify.com/v/um7PGw6T7xmirm083mHs

**ER**: order does not appear in the Explorer until the 1st owner signs the transaction

**Comment by alfetopito** [comment]
I believe this is a won't fix for now
Once the orders is sent to the wallet it is already created on the backend.

Also, the Safe tx associated with this order is not known AFAICT only from the order data.

We are good to release without this IMO.

@anxolin what do you think?

**Comment by elena-zh** [comment]
My concern is that orders do not appear in Explorer when we send them to EOA wallets: when we cancel them, they are not recorded to order list. 
But when we send them to SC-wallets, they appear..

**Comment by alfetopito** [comment]
Yeah, I agree, terrible UX, but that's what we have for now

**Comment by anxolin** [comment]
Yes, we discused it, and this has to be with a technical issue, and when we reviewed the options this was the less problematic solution. Agree is not great, but i think we can live with it for now
