### ISSUE TITLE
[2.4.0] Copy token icon does not present on all tokens

### ISSUE THREAD

**Issue by elena-zh** [gnosis/gp-ui#847]
Here is the order where there is no copy icon neat USDT token
https://protocol-explorer.staging.gnosisdev.com/orders/0xee93ae6a07ad2b8e8f05bfd6e40447334520234ec17b83b5df23fcc4c66ec1721f5b740436fc5935622e92aa3b46818906f416e96193b59f

**Expected**. copy icon should present

**Comment by matextrem** [comment]
@elena-zh I can see it ![image](https://user-images.githubusercontent.com/11525018/142435977-b226300a-820f-4ed2-bf08-fcba88d48ceb.jpeg)

**Comment by elena-zh** [comment]
@matextrem , Yes, thank you. 
I cleared all my local storage and in the end  was able to see it.
