### ISSUE TITLE
Transaction viewer: Add new page /tx/<hash>

### ISSUE THREAD

**Issue by elena-zh** [gnosis/gp-ui#851]
Related to #780

Add a new Transaction viewer page on Gnosis Protocol Explorer.
Page should be opened in the same tab when press on the transaction hash from an order detail. 

New endpoint from backend returning all orders settled in a given transaction
https://protocol-rinkeby.dev.gnosisdev.com/api/#/default/get_api_v1_transactions__txHash__orders
/api/v1/transactions/{txHash}/orders

**Comment by alfetopito** [comment]
> Page should be opened in a new tab when press on the transaction hash from an order detail.

I think we should keep in the same tab. Would open in new tab only external links

**Comment by elena-zh** [comment]
@alfetopito , description is updated.
