### ISSUE TITLE
Transaction viewer page: Implement new backend API interface

### ISSUE THREAD

**Issue by elena-zh** [gnosis/gp-ui#855]
Related to #780

Implement new backend API interface

New endpoint from backend returning all orders settled in a given transaction
https://protocol-rinkeby.dev.gnosisdev.com/api/#/default/get_api_v1_transactions__txHash__orders
`/api/v1/transactions/{txHash}/orders`

**Comment by alfetopito** [comment]
For context, it's something similar to https://github.com/gnosis/gp-ui/blob/develop/src/api/operator/operatorApi.ts#L180-L188
