### ISSUE TITLE
Transaction viewer page: Identify when tx is/is not a GPv2 transaction (offer link to blockexplorer)

### ISSUE THREAD

**Issue by elena-zh** [gnosis/gp-ui#857]
Related to #780

Identify when tx is/is not a GPv2 transaction (offer link to blockexplorer)

**Comment by alfetopito** [comment]
Thinking out loud, let me know if this makes sense.

When searching by a given tx hash:
- Verify it matches tx hash regex.
- If not, search not found page/ignore
- If yes, check in every network whether txs endpoint return anything
- If yes, show the tx orders page 
- If not, check whether there's a tx with given hash on the current network/all networks

What do you think of that?

**Comment by matextrem** [comment]
@alfetopito I think those comments are more related to [this](https://github.com/gnosis/gp-ui/issues/856) issue 

This issue is related to identify a gpv2 tx (in the tx list I guess) or am I wrong @elena-zh ?

**Comment by elena-zh** [comment]
@matextrem , I have just created the task based on the description in #780 
![image](https://user-images.githubusercontent.com/70885163/146889095-b9e382db-b243-441a-9706-a116bf40fbd7.png)

@alfetopito , could you please help to provide an answer?

**Comment by alfetopito** [comment]
> @alfetopito I think those comments are more related to [this](https://github.com/gnosis/gp-ui/issues/856) issue
> 
> This issue is related to identify a gpv2 tx (in the tx list I guess) or am I wrong @elena-zh ?

Well, somewhat.
To know when it's not a gp-v2 tx, we need to check whether its not present in any network.
I got caught up in thinking about that part and forgot about the goal of the task :sweat_smile: 

You can only offer a link to Etherscan/Blockscout when you are sure it's not one of ours and it's an existing tx.

**Comment by elena-zh** [comment]
The issue is about to be merged to Dev.
