### ISSUE TITLE
Redirect to a user details page when follow the link /address/<ens domain format> 

### ISSUE THREAD

**Issue by elena-zh** [gnosis/gp-ui#869]
Reported in https://github.com/gnosis/gp-ui/issues/828#issuecomment-978387640

1. Redirect a user to the user details page when follow the link  /address/<ens domain format, exists>
2. Redirect a user to the /search page when follow the link  /address/<ens domain format, does not exit>

Currently,  user is redirected to the 404 page

**Comment by alfetopito** [comment]
Follow up task https://github.com/gnosis/gp-ui/issues/884
