### ISSUE TITLE
Rebranding: Update Explorer URLs in Explorer 

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-ui#914]
**Description**

Update URLs used on explorer  to self identify its own stages: https://github.com/gnosis/gp-ui/blob/6620910e66f573684de86f914f456b0fff87cd21/webpack.config.js#L23-L26

**Proposal**

New prod URL: `explorer.cow.fi`
New barn URL: `barn.explorer.cow.fi`
*New staging URL: `staging.explorer.cow.fi`
*New staging URL: `dev.explorer.cow.fi`

* Still needs to confirm this will be the final domain

**Additional context**

**Comment by alfetopito** [comment]
Update: let's move forward with `prod` and `barn` but not update `dev` and `staging` yet.

Also, point the PR to a new branch called `rebranding` when ready (create the branch from `develop` if it doesn't exist yet)

**Comment by alongoni** [comment]
https://github.com/gnosis/gp-ui/tree/rebranding

**Comment by elena-zh** [comment]
I have created a separate task #943 for implementing new Staging URLs
*New staging URL: staging.explorer.cow.fi
*New staging URL: dev.explorer.cow.fi
