### ISSUE TITLE
Rebranding: Update Backend URLs in Explorer

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-ui#915]
**Description**

Update URLs used on explorer to talk to backend api: https://github.com/gnosis/gp-ui/blob/6620910e66f573684de86f914f456b0fff87cd21/webpack.config.js#L28-L33

**Proposal**

Prod urls per network:
- `api.cow.fi/mainnet`
- `api.cow.fi/rinkeby`
- `api.cow.fi/xdai`

*Staging urls per networks:
- `barn.api.cow.fi/mainnet`
- `barn.api.cow.fi/rinkeby`
- `barn.api.cow.fi/xdai`

*Still needs to confirm this will be the final domain

**Additional context**

**Comment by alfetopito** [comment]
Point the PR to a new branch called `rebranding` when ready (create the branch from `develop` if it doesn't exist yet)

**Comment by alongoni** [comment]
> Point the PR to a new branch called `rebranding` when ready (create the branch from `develop` if it doesn't exist yet)

I've created the `rebranding` [branch](https://github.com/gnosis/gp-ui/tree/rebranding)

**Comment by elena-zh** [comment]
I have created a separate task for not implemented changes related to updating staging URLs #944
