### ISSUE TITLE
Rename xDai to Gnosis Chain

### ISSUE THREAD

**Issue by alongoni** [gnosis/gp-ui#917]
**Description**
Task: Rename xDai to Gnosis Chain.
We should change all references in the UI.
Regarding the URL, we can keep both paths and redirect `/xdai/` to `/gc/`
![image](https://user-images.githubusercontent.com/622217/146814665-78cd3082-30a5-4746-b989-c25721bc2b5c.png)
![image](https://user-images.githubusercontent.com/622217/146818411-173878e4-4c9d-4cce-9fa4-8470681f0f62.png)

**Comment by alfetopito** [comment]
Update, the URL should be renamed from `/xdai` to `/gc`
