### ISSUE TITLE
Component name convention

### ISSUE THREAD

**Issue by W3stside** [gnosis/gp-ui#92]
From @anxolin

I vote against this naming convention. 
I prefer to call the dumb components without any suffix, they are just normal components.

First naming it `OrderWidgetView` u imply there's a 1<>1 relationship between OrderWidget and OrderWidgetView, which might be true here at least for now, although is not sth we always want to do. 

Another concern would be that the names get unnecesarilly complex. `MyCoolComponentWidgetViewStyledWrapperHoH` (disclaimer: some names in this film may or may not have been dramatized)

_Originally posted by @anxolin in https://github.com/gnosis/gp-ui/pull/91#discussion_r566684624_

Task: reconsider nomenclature

**Comment by alfetopito** [comment]
So, what are your suggestions?

**Comment by W3stside** [comment]
I am of no real opinion here, i do agree with @anxolin that a decoupled generic dumb component shouldbt be named too specifically. so for the OrdersWidgetView, if its always meant to be coupled to that then keep it else just name it DataView or sth

**Comment by alfetopito** [comment]
My goal with this decoupling is simply to isolate business logic from presentation and make testing (namely, Storybook) easier.
It's not intended to be generic enough to be used in isolation, thus there's still a high level of coupling between them.

As for the name, I don't care, whatever you prefer.

I can suggest a shorter version, that indicates what it is, without decoupling from the parent component:
From `OrderWidgetView` to `View` (which you probably won't like :shrug: )

**Comment by anxolin** [comment]
Decoupling I think is a good idea. I think is nice to have a component that represents the whole order. So I agree on that.
For me they are 100% independent, at least the dumb is independent of the Smart. The smart of course depend on the dumb.

For the naming, I would just eliminate any "sufix", just call it what you think it represents.

`OrderDetails` sound good to me. It would receive the order data, the fills array, and some callback for some actions that u can do in that page (if we can do any action) --> i.e. if we paginate the fills, which we can assume we don't do for now.

**Comment by alfetopito** [comment]
> `OrderDetails` sound good to me

Well, that's the name of the subcomponent https://github.com/gnosis/gp-ui/blob/develop/src/apps/explorer/components/OrderWidget/OrderDetails.tsx which has only the order table.
The fills are supposed to be a different sub-component, let's say `OrderFills`.

Which together compose `OrderWidget`

**Comment by anxolin** [comment]
The above works too. Initially I was thinking it's nice to have also the dumb component that aggregate the orderTable, orderFills, but I'm good and probably is enough to do it directly in the smart component (Widget)

If it ends up having some logic and markup, I would say is best to create a dumb for it too, so the widget just do the data fetching and delegating.

**Comment by alfetopito** [comment]
Ok, I got the message. How about this:

Refactor the component to be:

- apps/explorer/componets/OrderWigdget (already exists, will contain only logic, with hooks etc)
- components/common/OrderTable (will be extracted from https://github.com/gnosis/gp-ui/blob/develop/src/apps/explorer/components/OrderWidget/OrderDetails.tsx and contain only display logic)
- components/common/OrderDetails (will be extracted from https://github.com/gnosis/gp-ui/blob/develop/src/apps/explorer/components/OrderWidget/view.tsx and in the future will include <OrderFills>, also contain only display logic)

**Comment by anxolin** [comment]
Sounds great to me! The only change I would suggest to consider is:
 
I suggest this because:
* I think one criteria of grouping components could be: `prices`, `orders`, `trades`, `order-book`, `layout`, `common`. 
* Regarding the `common` could be for components like `Spinner`, `Modal`, `BlockExplorerLink` (smaller building blocks, with no big domain entity related)
* I think we'll find some stuff in the middle from old Mesa that most of the time we won't want to adapt. I suggest in those case to move them to a `v1` subfolder so we can deal with them later. i.e. `orders/v1`

WDYT?

**Comment by alfetopito** [comment]
Good idea, I like the sub-divisions
