### ISSUE TITLE
Update logos for Gnosis chain according to the media-kit

### ISSUE THREAD

**Issue by elena-zh** [gnosis/gp-ui#942]
https://github.com/gnosis/cowswap/pull/2023#issuecomment-1008832103

Additionally to the written name changes, can we also update the corresponding logos to this ones: https://www.xdaichain.com/media/media-kit

**Comment by elena-zh** [comment]
@alongoni , @alfetopito 
I have just noticed that we do not have logos in Explorer app. 
May be we need to add them? 
For now, as far as I understand, we need to update the chain colors. Correct?
![image](https://user-images.githubusercontent.com/70885163/148907544-2078ab46-d1ea-443f-81fe-5e4475cd2df0.png)

**Comment by alfetopito** [comment]
That's part of the design choice to not include it, so I would keep it as is.
The only thing to be done here would be the color.

**Comment by elena-zh** [comment]
Since under this task we should update Gnosis chain colors only, I would increase its scope and would suggest to change xDAI and wxDAI tokens' symbols like we have already implemented in https://github.com/gnosis/cowswap/pull/2122
